name             "beta-wordpress-permissions"
description      "Sets permissions to 755 on all folders within ./wp-content/uploads"
maintainer       "Betastream"
maintainer_email "dev@gbeta.io"
version          "1.0.0"
license           "GPL2"
